version = 0.1

[default.global.parameters]
stack_name = "Dash-CRM"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
stack_name = "Dash-CRM-dev"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "Dash-CRM-dev"
region = "us-east-2"
parameter_overrides = "StageName=\"dev\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev.deploy.parameters]
stack_name = "Dash-CRM-dev"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "Dash-CRM-dev"
parameter_overrides = "StageName=\"dev\""
region = "us-east-2"
image_repositories = []

[prod.deploy.parameters]
stack_name = "Dash-CRM-prod"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "Dash-CRM-prod"
parameter_overrides = "StageName=\"prod\""
region = "us-east-2"
image_repositories = []
