AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Projeto Base com SAM + API nomeada + Stage param

Globals:
  Function:
    Timeout: 3
    Runtime: python3.13
    Architectures:
      - x86_64

Parameters:
  StageName:
    Type: String
    Default: dev

Resources:

  # API nomeada e reutilizável
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${StageName}-MyApi"
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # Lambda de exemplo
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref MyApi

Outputs:

  HelloWorldEndpoint:
    Description: "Endpoint da função HelloWorld"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/hello"

  HelloWorldFunctionArn:
    Description: "ARN da Lambda HelloWorld"
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionRole:
    Description: "IAM Role criada implicitamente para a HelloWorldFunction"
    Value: !GetAtt HelloWorldFunctionRole.Arn
